apiVersion: v1
kind: ConfigMap
metadata:
  name: motion-tools-config
  namespace: motion-tools
data:
  APP_DOMAIN: "motion.example.com"
  APP_PROTOCOL: "https"
  BASE_LANGUAGE: "en"
  MULTISITE_MODE: "false"
  DB_HOST: "mariadb"
  DB_NAME: "antragsgruen"
  DB_USER: "antragsgruen"
  DB_PORT: "3306"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  RUN_MIGRATIONS: "true"
  MAIL_FROM_EMAIL: "noreply@motion.example.com"
  MAIL_FROM_NAME: "Motion Tools"
