apiVersion: v1
kind: Secret
metadata:
  name: motion-tools-secrets
  namespace: motion-tools
type: Opaque
stringData:
  DB_PASSWORD: "changeme"
  DB_ROOT_PASSWORD: "changeme-root"
  RANDOM_SEED: "generate-with-openssl-rand-base64-32"
  MAILER_DSN: "smtp://user:pass@smtp.example.com:587"
  REDIS_PASSWORD: ""
